export const CUSTOM_TEXT = {
  inteval: 3000,
  text_company: "Company Name",
  text_year: "2025",
  text_zoom_foto: "Zoom Foto",
  text_ya: "Ya",
  text_tidak: "Tidak",
  text_informasi: "Informasi",
  text_data_kosong: "Data Tidak Ditemukan !",
  text_data_pelanggan: "Data Pelanggan",
  text_konfirmasi_hapus: "Ingin Dihapus ?",
  text_sukses_hapus: "Berhasil Dihapus",
  text_gagal_hapus: "Gagal Dihapus !",
  text_tambah_data: "Tambah Data",
  text_refresh_data: "Refresh Data",
  text_cari_data: "Cari Data",
  text_loading: "Mohon Tunggu ...",
  text_aksi: "Aksi",
  text_nomor: "Nomor",
  text_nama: "Nama",
  text_alamat: "Alamat",
  text_telepon: "Telepon",
  text_foto: "Foto",

  dir_images: "images",
  dir_uploads: "uploads",

  file_logo: "logo.png",
  file_noimage: "noimage.png",
};