const pelanggan = "Pelanggan";
const format_isi = "Format Isi"
export const CUSTOM_TEXT = {
  inteval: 3000,
  text_company: "Company Name",
  text_year: "2025",
  text_zoom_foto: "Zoom Foto",
  text_ya: "Ya",
  text_tidak: "Tidak",
  text_informasi: "Informasi",
  text_data_kosong: "Data Tidak Ditemukan !",
  text_data_pelanggan: `Data ${pelanggan}`,
  text_konfirmasi_hapus: "Ingin Dihapus ?",
  text_sukses_hapus: "Berhasil Dihapus",
  text_gagal_hapus: "Gagal Dihapus !",
  text_sukses_simpan: "Berhasil Disimpan",
  text_gagal_simpan: "Gagal Disimpan !",
  text_sukses_ubah: "Berhasil Diubah",
  text_gagal_ubah: "Gagal Diubah !",
  text_wajib_isi: "Harus Diisi !",
  text_wajib_pilih: "Harus Dipilih !",
  text_wajib_isi_pilih: "Harus Diisi / Dipilih !",
  text_tampil_data: "Tampil Data",
  text_tambah_data: "Tambah Data",
  text_ubah_data: "Ubah Data",
  text_refresh_data: "Refresh Data",
  text_cari_data: "Cari Data",
  text_loading: "Mohon Tunggu ...",
  text_pelanggan: `${pelanggan}`,
  text_aksi: "Aksi",
  text_nomor: "Nomor",
  text_nama: "Nama",
  text_alamat: "Alamat",
  text_telepon: "Telepon",
  text_foto: "Foto",
  text_simpan: "Simpan",
  text_ubah: "Ubah",
  text_batal: "Batal",

  format_isi_angka : `${format_isi} : 0-9`,
  format_isi_nama : `${format_isi} : a-zA-Z .,`,
  format_isi_text : `${format_isi} : a-zA-Z `,
  format_isi_text_plus : `${format_isi} : 0-9a-zA-Z '"-.,`,


  dir_images: "images",
  dir_uploads: "uploads",

  file_logo: "logo.png",
  file_noimage: "noimage.png",
};